### ISSUE TITLE
Linux Foundation Directed Fund Participation

### ISSUE THREAD

**Issue by irmerk** [accordproject/technical-steering-committee#19]
# Discussion 🗣
This is tracking the proposal for [Accord Project Sponsorship Packages](https://docs.google.com/document/d/19eePzfYZYMDYoXNA6WCRmSkiV-BWXPD5JWyxZdXvQuE/edit)

### Why Sponsor?

**Connect** with the global Accord Project Community
**Support** the development and implementation of Accord Project (a Linux Foundation project)
**Inspire** legal technology growth and educational efforts worldwide

### Where does my money go?

- Maintenance and operation of domains
- Working with international standards bodies
- Accord Project presence at IT events
- Sprints, development, and other services
- Accord Project Forum and other Accord Project events
- Taxes, accounting, and legal expenses
- Other qualified expenses as decided by the elected Technical Steering Committee

##### $5k per year
- Small logo placed on our Sponsors page with a link to your site and a short bio of your company.
- Bronze Corporate Sponsor badge for your website

##### $10k per year
- Small logo placed on our Sponsors page with a link to your site and a short bio of your company.
- Silver Corporate Sponsor badge for your website
- Logo on templates.accordproject.org, models.accordproject.org.
- Joint press release with Accord Project and your company
- One post a year on accordproject.org and official Twitter account

##### $15k per year
- Medium logo placed on our Sponsors page with a link to your site and a short bio of your company.
- Logo on docs.accordproject.org, templates.accordproject.org, models.accordproject.org.
- Gold Corporate Sponsor badge for your website
- Joint press release with Accord Project and your company
- Two post a year on accordproject.org and official Twitter account

##### $25k per year
- Large logo prominently placed on our Sponsors page with a link to your site and a short bio of your company.
- Logo on accordproject.org, docs.accordproject.org, templates.accordproject.org, models.accordproject.org.
- Platinum Corporate Sponsor badge for your website
- Joint press release with Accord Project and your company
- Four posts a year on accordproject.org and official Twitter account

##### From $5 to $1000
- Support the Open Source projects that you use!
- Your name listed on our community sponsor page (optional)
- Our gratitude!

---

_**Please note**_:
_Acceptance of sponsorship from an individual or organization does not imply endorsement of that sponsor by the Accord Project_.
_Acceptance of a sponsorship is at the discretion of Accord Project_.

**Comment by martinhalford** [comment]
ACTION: Antonis.

**Comment by martinhalford** [comment]
@anton1s - attempting to get 30 mins time with Linux Foundation to discuss options and potential issues with AP becoming a 502(c)3 organisation. General consensus that AP needs to be the master of its own destiny and have a process/system in place that would serve the organisation for many TSC Boards and years into the future.

**Comment by martinhalford** [comment]
[From TSC Meeting 2021-02-25]
- In order for the Accord Project to offer sponsorship packages then first need to be able to manage its own finances.

1. Crowdfunding - ability to seek funds from individuals on an ad hoc basis based on funding goals and expensing costs against money raised.
2. Own non-profit legal entity - fully incorportated with 501(c)(3) charity status. LegalZoom offer a service to help manage this entity on our behalf (Initally $1500 plus $300 annually). Will take 3 months to setup. Can become complicated and take longer to setup if the amount of money being raised exceeds $50,000.
3. Umbrella bank account service via Linux Foundation - need more information. Reaching out to LF for more details.

- Key requirement is that, for whatever option selected, it is long-term and can be easily managed by future TSC members.
- ACTION: Reach out to LF (Antonis), followup with Dan S and Peter H re: previous attempts at setting up entity and continue discussions on Slack.

**Comment by martinhalford** [comment]
See Exceptional TSC Meeting Notes 
https://github.com/accordproject/technical-steering-committee/blob/master/Meeting%20Notes/2021-03-04.md

**Comment by martinhalford** [comment]
[From TSC Meeting 2021-03-25]

```
- Antonis & Tom provided an update.
- Regarding Linux Foundation Membership model 
	- Expenses:
		- LF entity receives invoices from suppliers who pay on AP's behalf.
		- AP approvers board approves expenses.
	- Employees:
		- Can employee AP staff under LF Membership Model as "subsidiary" entity.
		- LF would handle legal liabilities of disputes.
		- LF also have their own staff that can be deployed to AP as employees (e.g. Admin staff) at about 1.4x market rate.
		- LF can allocate resources as low as 25% full-time utilisation.
	- Exit clause:
		- AP commits to 1 year then reverts to a month-to-month arrangement.
	- Fee:
		- 9% of funds raised.
- Suggest that the next step is to review the contract that was drafted a year or so back with a view to AP using LF Membership Model

- **MOTION** 
	- That AP proceeds with contract negotiations with Linux Foundation subject to final approval by TSC and AP Governing Board.
	- **CARRIED UNANIMOUS**

- **ACTION**
	- Begin negotiations with LF, and involve Peter Hunn and Dan Selman.
```

**Comment by martinhalford** [comment]
[From TSC Meeting 2021-04-29]

- Peter Hunn presented the completed "Accord Foundation Participation Agreement and Funding Charter" agreement.
- Peter provided overview of proposed Membership terms, how these would contribute to funding as well as the costs involved.
- Oliver Tod raised question regarding legacy members - previously free. 
- General consensus that legacy members would need to sign up under the new agreement.
- Potential for some sort of "used by" or "friends of..." or "legacy members of..." list - participants of which would not receive the benefits of Premier, General or Accociate.
- Agreement document shared with TSC Members so TSC Members are able to review and raise any objections before 4pm ET on Monday 3 May.
- **MOTION** 
	- To execute the "Directed Fund Participation Agreement" under the Linux Foundation, subject to no objections being raised by TSC Members prior to 4pm US Eastern Time, Monday 3 May 2021. 
	- **CARRIED UNANIMOUSLY by TSC Members on call + Antonis in absentia**

**Comment by martinhalford** [comment]
Hi All, 

I have an objection to the "Directed Fund Participation Agreement" presented to the TSC on 29 Apr 2021 - specifically the requirement that companies wanting to join the Accord Project must be members of the Linux Foundation first in "Exhibit C".  

Linux Foundation Membership for ordinary companies starts at USD $5000 and goes up to $20,000 depending on the size of the entity.  This is a non-trivial financial penalty to impose on prospective Accord Project Members.  I'm sure many prospective members would rather this money benefited the Accord Project directly!

Given that the Linux Foundation will be taking a percentage of all membership fees received by Accord Project in order to administer the corporate accounts etc, can we please request this requirement be removed due to the very real possibility that it will prevent some prospective Accord Project companies becoming members? 

If the Linux Foundation is unwilling to remove this requirement can we please request an explanation regarding the legal and/or commercial justifications for this clause?

Also, while we're at it... Can we please confirm that the Accord Project is free to determine the Membership Fees independently of any Linux Foundation rules or precedents?

Thoughts?

@peterhunn @dselman @jeromesimeon @irmerk @anton1s @niallroche

**Comment by peterhunn** [comment]
Thanks @martinhalford. I'll reach out to the LF to see what their position is on this point. I suspect that it is a standard across all projects, but can't hurt to ask and get more background.

**Comment by martinhalford** [comment]
From TSC Meeting: Thursday 27 May, 2021:

- Following on from the [2021-05-20 Exceptional TSC Meeting](https://github.com/accordproject/technical-steering-committee/blob/master/Meeting%20Notes/2021-04-29.md), all TSC Members expressed approval to proceed with executing the "Directed Fund Participation Agreement" under the Linux Foundation.
- @martinhalford commented that it should not be the Accord Project's role to police Accord Project Member's Linux Foundation Membership.
- **MOTION**
To execute the "Directed Fund Participation Agreement" under the Linux Foundation.
**CARRIED UNANIMOUSLY** by TSC Members on call + Tom Brooke in absentia
- TSC delegated Tom Brooke to initiate signing of agreement with the Linux Foundation. (Thanks Tom!)

**Comment by tbrooke** [comment]
Update on Directed Fund Participation

We are proceeding with the directed fund participation. I have spoken with Scott from the Linux Foundation a few time and he has clarified a some issues. Martin and I also had a conversation and we feel comfortable with proceeding. Scott will forward us docs to sign in order to start our participation under the member program. Since we do not have any members at this point it will remain in limbo. We are already a "series LLC" so we are a legal entity within the Linux Foundation. Scott also emphasized the Crowdfunding LXF portal [LXF Crowdfunding](https://lfx.linuxfoundation.org/tools/crowdfunding/) that we can use by simply opening an entry. The crowdfunding portal is reimbursement based so the funds received are held by the Linux Foundation and then when we authorize payment for reimbursement it is paid-- The portal has a public  accounting for the funds so contributors can see how their funds are spent.

Our next steps are to: 1) receive the docs and sign them  2) look for members   3) utilize the Crowdfunding portal pending enough members to provide a funding base until we get member on board

**Comment by martinhalford** [comment]
Thanks @tbrooke for following up with LF and for the update. Sounds like a plan!

**Comment by martinhalford** [comment]
1. Determine credit cards in use.
2. Determine CC going fwd.
3. Seek operating cash from CrowdFunding.
4. Seek Members.

**Comment by jeromesimeon** [comment]
@martinhalford now that some level of funding seems to be happening. I thought I would try and suggest priorities for things to migrate to the new funding model:

## do first
1. Netlify (this is our main day-to-day deployment platform for things like: Ergo REPL, models, templates, storybook etc). Do we want to consider other options? e.g., Heroku? This is also more work since we'll need to re-create the deployment once we get an Accord Project account.
2. Word press hosting

## do second
3. gsuite
4. (not sure if we're using free tier on those) Vimeo, 1password

## the rest
5. ???

**Comment by martinhalford** [comment]
@jeromesimeon: Good idea. Here's the sheet of existing expenses that @dselman put together some time ago.  We can add to this as additional expenses are uncovered.

[Accord Project - Operational Expenditure](https://docs.google.com/spreadsheets/d/1a04jMYpGCVONVPuUHEovdvN4S-sgNfgBauF_DRcJdbQ/edit#gid=0)

At least, we can now start reimbursing people/orgs that are currently incurring these expenses.  So, the first part of the issue (i.e. AP paying for itself) is kinda solved (provided donors keep contributing).

This would definitely be a good time to revisit who is responsible for paying these bills and/or which services we want to continue using.  Obviously you, @dselman and @mttrbrts will have the most insight into the pros and cons of changing services.

**Comment by martinhalford** [comment]
From TSC Meeting 26 Aug 2021:

- Funding portal now live and taking donations at: 
[https://crowdfunding.lfx.linuxfoundation.org/projects/accordproject](https://crowdfunding.lfx.linuxfoundation.org/projects/accordproject)
- Priority to make sure DNS is under appropriate control.
- Netlify and WordPress need to be migrated from Clause.io and into an Accord Project account.
- (Note: There have been some reliability issues with Netlify which might prompt us migrating to an alternative - to be discussed.)
- **ACTION** 
	- Jerome to do some investigation to find out who currently controls the DNS, and how to migrate Netlify to an Accord Project account.
	- WordPress may need to wait for time-being.
	- Reach out to current card holders to ask if they want to be reimbursed for current charges.

**Comment by martinhalford** [comment]
DNS registration and domain records controlled by Wordpress.com - therefore under AP management.
Martin to follow up with Dan on credit card - update Ops Exp sheet.

**Comment by martinhalford** [comment]
From TSC meeting on 02-12-2002:

- Sponsorship document at: https://docs.google.com/document/d/19eePzfYZYMDYoXNA6WCRmSkiV-BWXPD5JWyxZdXvQuE/edit#heading=h.2fk39zpebxf5
- Accord Project community feedback was positive.
- Agreed to move forward with Sponsorhsip Packages as detailed in above document.
- To be published to Accord Project web site (Thank you Michael Grover!)

**ACTIONS**
- Martin to write blog article promoting Sponsorship packages.
- Michael Grover to publish to AP web site.

**Comment by martinhalford** [comment]
Following blog post draft attached.  To be published to Accord Project web site in "News" section.

[Help shape the future of Smart Legal Contracts.md](https://github.com/accordproject/technical-steering-committee/files/7922210/Help.shape.the.future.of.Smart.Legal.Contracts.md)

**Comment by martinhalford** [comment]
Blog posted at: https://accordproject.org/news/help-shape-the-future-of-smart-legal-contracts/

Issue completed.
