### ISSUE TITLE
Standardise approach to CI/CD

### ISSUE THREAD

**Issue by dselman** [accordproject/technical-steering-committee#4]
Accord Project currently uses the following CI/CD tools:
- https://travis-ci.org
- https://circleci.com

Many of the projects use Travis to run tests and to publish code artefacts when a GitHub release is created. For example, pushing the VSCode extension to the VSCode extension marketplace.

We have also been experimenting with GitHub Actions.

**Comment by irmerk** [comment]
Looking at all three, I get the impression that CircleCI has the best option for open source.

**Comment by jeromesimeon** [comment]
> Looking at all three, I get the impression that CircleCI has the best option for open source.

I really like CircleCI (better machines, more readable logs, longer builds), but when I had checked some months ago I shied away from it because I wasn't sure if we could port our deploy scripts (or how hard it would be to do). It's also a bit less mainstream, so there is a question of long term support.

**Comment by jeromesimeon** [comment]
A proposed resolution to this: switch to GitHub Actions.
A first PR showing how to do so is available for review here: https://github.com/accordproject/concerto/pull/219

A few notes:
- Appears much faster than TravisCI
- Much simpler scripts, should help with maintenance
- Still need review & test on an actual versioned release (only timestamped release has been tested so far)
- Still need to try and switch the Ergo compiler building process (currently in CircleCI) to GitHub Actions as well

**Comment by jeromesimeon** [comment]
We're ready to move to GitHub Actions as a replace meant for CircleCI. It has been used and validated on the latest https://github.com/accordproject/concerto/releases/tag/v1.0.0-alpha.2 release.

Still to do:
- [ ] Migrate all the other repos, and disable Travis
- [ ] Migrate the Ergo compiler build from source from CircleCI

**Comment by irmerk** [comment]
@jeromesimeon I'd love to do at least one of these migrations. The list as I can think of it:

- [ ] `ergo`
- [ ] `cicero`
- [ ] `markdown-transform`
- [ ] `web-components`
- [ ] `cicero-vscode-extension`
- [ ] `cicero-template-library`
- [ ] `techdocs`

Ones that seem to not use Travis or Circle:

- [ ] `techdocs`
- [ ] `template-studio`
- [ ] `models`

Care to pair on one together, then I can do `web-components`?

**Comment by martinhalford** [comment]
Now with Maintainers. Leaving open for PRs.

**Comment by jeromesimeon** [comment]
> @jeromesimeon I'd love to do at least one of these migrations. The list as I can think of it:
> 
> * [ ]  `ergo`
> * [ ]  `cicero`
> * [ ]  `markdown-transform`
> * [ ]  `web-components`
> * [ ]  `cicero-vscode-extension`
> * [ ]  `cicero-template-library`
> * [ ]  `techdocs`
> 
> Ones that seem to not use Travis or Circle:
> 
> * [ ]  `techdocs`
> * [ ]  `template-studio`
> * [ ]  `models`
> 
> Care to pair on one together, then I can do `web-components`?

The official list based on Travis itself:
* [ ]  `concerto`
* [ ]  `ergo`
* [ ]  `cicero`
* [ ]  `markdown-transform`
* [ ]  `web-components`
* [ ]  `cicero-vscode-extension`
* [ ]  `cicero-template-library`

**Comment by jeromesimeon** [comment]
A checklist:

**Preparation**
- [ ] Decide on node.js version strategy for AP (currently we are on node `10` but some project seem to think otherwise)
- [ ] Decide on build policy: all branches and PRs? only master? only PRs on master?
- [ ] Consolidate concerto build files (notably borrowed from recent improvements / changes in `cicero`)

**Switch Projects**
- [ ] Concerto
   - [ ] Remove secrets from Travis (for AP maintainers: in Travis Repository Settings)
   - [ ] Disable Travis in the configuration (for AP maintainers: Travis Personal Profile > Settings > Accord Project
   - [ ] Remove `.travis.yml` and `.travis` directories in repo
   - [ ] Add `.github/workflows` directory based on those in `./concerto/.github/workflows`
   - [ ] Remove scripts in `./scripts` replace by those found in `./concerto/scripts`
   - [ ] Fix `package.json` notable adjustments: remove some of the old scripts, make sure code coverage works
   - [ ] Test build on PR with timestamps
   - [ ] Test build on GitHub release with version number
- [ ] Cicero
   - [ ] Remove secrets from Travis (for AP maintainers: in Travis Repository Settings)
   - [ ] Disable Travis in the configuration (for AP maintainers: Travis Personal Profile > Settings > Accord Project
   - [ ] Remove `.travis.yml` and `.travis` directories in repo
   - [ ] Add `.github/workflows` directory based on those in `./concerto/.github/workflows`
   - [ ] Remove scripts in `./scripts` replace by those found in `./concerto/scripts`
   - [ ] Fix `package.json` notable adjustments: remove some of the old scripts, make sure code coverage works
   - [ ] Test build on PR with timestamps
   - [ ] Test build on GitHub release with version number
- [ ] Ergo
   - [ ] Remove secrets from Travis (for AP maintainers: in Travis Repository Settings)
   - [ ] Disable Travis in the configuration (for AP maintainers: Travis Personal Profile > Settings > Accord Project
   - [ ] Remove `.travis.yml` and `.travis` directories in repo
   - [ ] Add `.github/workflows` directory based on those in `./concerto/.github/workflows`
   - [ ] Remove scripts in `./scripts` replace by those found in `./concerto/scripts`
   - [ ] Fix `package.json` notable adjustments: remove some of the old scripts, make sure code coverage works
   - [ ] Test build on PR with timestamps
   - [ ] Test build on GitHub release with version number
- [ ] Markdown Transform
   - [ ] Remove secrets from Travis (for AP maintainers: in Travis Repository Settings)
   - [ ] Disable Travis in the configuration (for AP maintainers: Travis Personal Profile > Settings > Accord Project
   - [ ] Remove `.travis.yml` and `.travis` directories in repo
   - [ ] Add `.github/workflows` directory based on those in `./concerto/.github/workflows`
   - [ ] Remove scripts in `./scripts` replace by those found in `./concerto/scripts`
   - [ ] Fix `package.json` notable adjustments: remove some of the old scripts, make sure code coverage works
   - [ ] Test build on PR with timestamps
   - [ ] Test build on GitHub release with version number
- [ ] Web Components
   - [ ] Remove secrets from Travis (for AP maintainers: in Travis Repository Settings)
   - [ ] Disable Travis in the configuration (for AP maintainers: Travis Personal Profile > Settings > Accord Project
   - [ ] Remove `.travis.yml` and `.travis` directories in repo
   - [ ] Add `.github/workflows` directory based on those in `./concerto/.github/workflows`
   - [ ] Remove scripts in `./scripts` replace by those found in `./concerto/scripts`
   - [ ] Fix `package.json` notable adjustments: remove some of the old scripts, make sure code coverage works
   - [ ] Test build on PR with timestamps
   - [ ] Test build on GitHub release with version number
- [ ] Cicero VSCode Extension
   - [ ] Remove secrets from Travis (for AP maintainers: in Travis Repository Settings)
   - [ ] Disable Travis in the configuration (for AP maintainers: Travis Personal Profile > Settings > Accord Project
   - [ ] Remove `.travis.yml` and `.travis` directories in repo
   - [ ] Add `.github/workflows` directory based on those in `./concerto/.github/workflows`
   - [ ] Remove scripts in `./scripts` replace by those found in `./concerto/scripts`
   - [ ] Fix `package.json` notable adjustments: remove some of the old scripts, make sure code coverage works
   - [ ] Test build on PR with timestamps
   - [ ] Test build on GitHub release with version number
- [ ] Cicero Template Library
   - [ ] Remove secrets from Travis (for AP maintainers: in Travis Repository Settings)
   - [ ] Disable Travis in the configuration (for AP maintainers: Travis Personal Profile > Settings > Accord Project
   - [ ] Remove `.travis.yml` and `.travis` directories in repo
   - [ ] Add `.github/workflows` directory based on those in `./concerto/.github/workflows`
   - [ ] Remove scripts in `./scripts` replace by those found in `./concerto/scripts`
   - [ ] Fix `package.json` notable adjustments: remove some of the old scripts, make sure code coverage works
   - [ ] Test build on PR with timestamps
   - [ ] Test build on GitHub release with version number

**Cleanup**
- [ ] Remove all Travis dependencies in org (apps, etc)

**Comment by rkotangoor** [comment]
> > @jeromesimeon I'd love to do at least one of these migrations. The list as I can think of it:
> > 
> > * [ ]   `ergo`
> > * [ ]   `cicero`
> > * [ ]   `markdown-transform`
> > * [ ]   `web-components`
> > * [ ]   `cicero-vscode-extension`
> > * [ ]   `cicero-template-library`
> > * [ ]   `techdocs`
> > 
> > Ones that seem to not use Travis or Circle:
> > 
> > * [ ]   `techdocs`
> > * [ ]   `template-studio`
> > * [ ]   `models`
> > 
> > Care to pair on one together, then I can do `web-components`?
> 
> The official list based on Travis itself:
> 
> * [ ]   `concerto`
> * [ ]   `ergo`
> * [ ]   `cicero`
> * [ ]   `markdown-transform`
> * [ ]   `web-components`
> * [ ]   `cicero-vscode-extension`
> * [ ]   `cicero-template-library`

from this list is there anything I can pick up? @jeromesimeon or @irmerk? Please let me know if you are okay pairing on web-components @irmerk

**Comment by jeromesimeon** [comment]
This item has been completed:
1. All projects have been migrated to GitHub actions
2. All references to previous CI service (Travis) have been removed
3. Travis access to AP repositories and secrets in Travis have been removed
4. All the new GitHub actions scripts have been tested and work for both development/testing and for publication of new releases (Tested in the recent `0.22` release).

Ergo still uses CircleCI for "build from source" jobs, but I believe this is fine and separate migration can be considered in the future.
